from Preprocessors import Preprocessor
import pandas as pd
from sklearn import preprocessing as pp

vk_data = pd.read_csv("../Data/vk_data.csv")

encoder = pp.LabelEncoder()
discretizer = pp.KBinsDiscretizer(n_bins=5, encode='ordinal', strategy='uniform')

p = Preprocessor([('encoder', encoder), ('discretizer', discretizer)])

data, en = p.apply(vk_data)
for i, j in en.items():
    print(f"{i}:{j}")
"""
about_topic:{'no': 0, 'sbj_0_0': 1, 'sbj_0_1': 2, 'sbj_0_10': 3, 'sbj_0_11': 4, 'sbj_0_12': 5, 'sbj_0_13': 6, 'sbj_0_14': 7, 'sbj_0_15': 8, 'sbj_0_16': 9, 'sbj_0_17': 10, 'sbj_0_18': 11, 'sbj_0_19': 12, 'sbj_0_2': 13, 'sbj_0_20': 14, 'sbj_0_21': 15, 'sbj_0_22': 16, 'sbj_0_23': 17, 'sbj_0_24': 18, 'sbj_0_25': 19, 'sbj_0_26': 20, 'sbj_0_27': 21, 'sbj_0_28': 22, 'sbj_0_29': 23, 'sbj_0_3': 24, 'sbj_0_30': 25, 'sbj_0_31': 26, 'sbj_0_4': 27, 'sbj_0_5': 28, 'sbj_0_6': 29, 'sbj_0_7': 30, 'sbj_0_8': 31, 'sbj_0_9': 32}
activities_topic:{'no': 0, 'sbj_0_0': 1, 'sbj_0_1': 2, 'sbj_0_10': 3, 'sbj_0_11': 4, 'sbj_0_12': 5, 'sbj_0_13': 6, 'sbj_0_14': 7, 'sbj_0_15': 8, 'sbj_0_16': 9, 'sbj_0_17': 10, 'sbj_0_18': 11, 'sbj_0_19': 12, 'sbj_0_2': 13, 'sbj_0_20': 14, 'sbj_0_21': 15, 'sbj_0_22': 16, 'sbj_0_23': 17, 'sbj_0_24': 18, 'sbj_0_25': 19, 'sbj_0_26': 20, 'sbj_0_27': 21, 'sbj_0_28': 22, 'sbj_0_29': 23, 'sbj_0_3': 24, 'sbj_0_30': 25, 'sbj_0_31': 26, 'sbj_0_4': 27, 'sbj_0_5': 28, 'sbj_0_6': 29, 'sbj_0_7': 30, 'sbj_0_8': 31, 'sbj_0_9': 32}
interests_topic:{'no': 0, 'sbj_0_0': 1, 'sbj_0_1': 2, 'sbj_0_10': 3, 'sbj_0_11': 4, 'sbj_0_12': 5, 'sbj_0_13': 6, 'sbj_0_15': 7, 'sbj_0_16': 8, 'sbj_0_17': 9, 'sbj_0_18': 10, 'sbj_0_19': 11, 'sbj_0_2': 12, 'sbj_0_20': 13, 'sbj_0_21': 14, 'sbj_0_22': 15, 'sbj_0_23': 16, 'sbj_0_24': 17, 'sbj_0_25': 18, 'sbj_0_26': 19, 'sbj_0_27': 20, 'sbj_0_28': 21, 'sbj_0_29': 22, 'sbj_0_3': 23, 'sbj_0_30': 24, 'sbj_0_31': 25, 'sbj_0_4': 26, 'sbj_0_5': 27, 'sbj_0_6': 28, 'sbj_0_7': 29, 'sbj_0_8': 30, 'sbj_0_9': 31}
top1_interes:{'beauty, hair, manicure, salon': 0, 'book, reading, language, word, literature': 1, 'car, cars, sale, tires': 2, 'client, project, internet, business, company': 3, 'color, flowers, interior, design': 4, 'dress, fashion, color, style': 5, 'film, series, cinema, genre': 6, 'football, match, russia, team, goalkeeper': 7, 'game, team, competition, sport': 8, 'handmade, materials, products': 9, 'home, renovation, decoration, installation': 10, 'ingredients, cooking, dishes, salt, spices': 11, 'iphone, apple, technology, equipment, smartphone': 12, 'massage, meditation, yoga': 13, 'music, concerts, rock, tickets, festivals': 14, 'participation, festival, exhibition': 15, 'photographer, photography, show, wedding, photographer': 16, 'sale, clothes, size, price, sewing': 17, 'school, education, question, topic': 18, 'shop, price, gifts, internet': 19, 'skin, face, care, cosmitology': 20, 'theater, performance, actors': 21, 'treatment, doctors, tests, clinic, health': 22, 'vacation, sea, accommodation, cost': 23, 'war, history, army, politics': 24, 'work, schedule, earnings, money': 25}
top2_interes:{'beauty, hair, manicure, salon': 0, 'book, reading, language, word, literature': 1, 'car, cars, sale, tires': 2, 'client, project, internet, business, company': 3, 'color, flowers, interior, design': 4, 'dress, fashion, color, style': 5, 'film, series, cinema, genre': 6, 'football, match, russia, team, goalkeeper': 7, 'game, team, competition, sport': 8, 'handmade, materials, products': 9, 'home, renovation, decoration, installation': 10, 'ingredients, cooking, dishes, salt, spices': 11, 'iphone, apple, technology, equipment, smartphone': 12, 'massage, meditation, yoga': 13, 'music, concerts, rock, tickets, festivals': 14, 'participation, festival, exhibition': 15, 'photographer, photography, show, wedding, photographer': 16, 'sale, clothes, size, price, sewing': 17, 'school, education, question, topic': 18, 'shop, price, gifts, internet': 19, 'skin, face, care, cosmitology': 20, 'theater, performance, actors': 21, 'treatment, doctors, tests, clinic, health': 22, 'vacation, sea, accommodation, cost': 23, 'war, history, army, politics': 24, 'work, schedule, earnings, money': 25}
top3_interes:{'beauty, hair, manicure, salon': 0, 'book, reading, language, word, literature': 1, 'car, cars, sale, tires': 2, 'client, project, internet, business, company': 3, 'color, flowers, interior, design': 4, 'dress, fashion, color, style': 5, 'film, series, cinema, genre': 6, 'football, match, russia, team, goalkeeper': 7, 'game, team, competition, sport': 8, 'handmade, materials, products': 9, 'home, renovation, decoration, installation': 10, 'ingredients, cooking, dishes, salt, spices': 11, 'iphone, apple, technology, equipment, smartphone': 12, 'massage, meditation, yoga': 13, 'music, concerts, rock, tickets, festivals': 14, 'participation, festival, exhibition': 15, 'photographer, photography, show, wedding, photographer': 16, 'sale, clothes, size, price, sewing': 17, 'school, education, question, topic': 18, 'shop, price, gifts, internet': 19, 'skin, face, care, cosmitology': 20, 'theater, performance, actors': 21, 'treatment, doctors, tests, clinic, health': 22, 'vacation, sea, accommodation, cost': 23, 'war, history, army, politics': 24, 'work, schedule, earnings, money': 25}
top4_interes:{'beauty, hair, manicure, salon': 0, 'book, reading, language, word, literature': 1, 'car, cars, sale, tires': 2, 'client, project, internet, business, company': 3, 'color, flowers, interior, design': 4, 'dress, fashion, color, style': 5, 'film, series, cinema, genre': 6, 'football, match, russia, team, goalkeeper': 7, 'game, team, competition, sport': 8, 'handmade, materials, products': 9, 'home, renovation, decoration, installation': 10, 'ingredients, cooking, dishes, salt, spices': 11, 'iphone, apple, technology, equipment, smartphone': 12, 'massage, meditation, yoga': 13, 'music, concerts, rock, tickets, festivals': 14, 'participation, festival, exhibition': 15, 'photographer, photography, show, wedding, photographer': 16, 'sale, clothes, size, price, sewing': 17, 'school, education, question, topic': 18, 'shop, price, gifts, internet': 19, 'skin, face, care, cosmitology': 20, 'theater, performance, actors': 21, 'treatment, doctors, tests, clinic, health': 22, 'vacation, sea, accommodation, cost': 23, 'war, history, army, politics': 24, 'work, schedule, earnings, money': 25}
top5_interes:{'beauty, hair, manicure, salon': 0, 'book, reading, language, word, literature': 1, 'car, cars, sale, tires': 2, 'client, project, internet, business, company': 3, 'color, flowers, interior, design': 4, 'dress, fashion, color, style': 5, 'film, series, cinema, genre': 6, 'football, match, russia, team, goalkeeper': 7, 'game, team, competition, sport': 8, 'handmade, materials, products': 9, 'home, renovation, decoration, installation': 10, 'ingredients, cooking, dishes, salt, spices': 11, 'iphone, apple, technology, equipment, smartphone': 12, 'massage, meditation, yoga': 13, 'music, concerts, rock, tickets, festivals': 14, 'participation, festival, exhibition': 15, 'photographer, photography, show, wedding, photographer': 16, 'sale, clothes, size, price, sewing': 17, 'school, education, question, topic': 18, 'shop, price, gifts, internet': 19, 'skin, face, care, cosmitology': 20, 'theater, performance, actors': 21, 'treatment, doctors, tests, clinic, health': 22, 'vacation, sea, accommodation, cost': 23, 'war, history, army, politics': 24, 'work, schedule, earnings, money': 25}
"""
